### ISSUE TITLE
是否能支持GUID方式获取驱动设备路径？

### ISSUE THREAD

**Issue by Jayukie** [k0keoyo/kDriver-Fuzzer#4]
遇到windows驱动未直接对devicename做符号连接给应用程序调用的情况，而是通过GUID的方式间接获取devicename，看是否能够增加此方式的兼容，以GUID作为程序输入
详细可参考：
https://cloud.tencent.com/developer/article/1597613
https://blog.csdn.net/weixin_30745641/article/details/99575978

**Comment by k0keoyo** [comment]
你好，感谢建议，由于工作原因我很长时间都没有维护更新这个项目代码了。
如果有想法可以直接修改，如果可能的话可以push给我，我来merge，感谢：）
----- Original Message -----
